# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coutry_code', models.IntegerField(db_index=True)),
                ('district_code', models.IntegerField(db_index=True)),
                ('comm_code', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.IntegerField(choices=[(1, b'Przedszkole'), (3, b'Szko\xc5\x82a podstawowa'), (4, b'Gimnazjum'), (13, b'Zasadnicza szko\xc5\x82a zawodowa'), (14, b'Liceum og\xc3\xb3lnokszta\xc5\x82c\xc4\x85ce'), (15, b'Liceum profilowane'), (16, b'Technikum'), (17, b'Liceum og\xc3\xb3lnokszta\xc5\x82c\xc4\x85ce uzupe\xc5\x82niaj\xc4\x85ce dla absolwent\xc3\xb3w zasadniczych szk\xc3\xb3\xc5\x82 zawodowych'), (18, b'Technikum uzupe\xc5\x82niaj\xc4\x85ce dla absolwent\xc3\xb3w zasadniczych szk\xc3\xb3\xc5\x82 zawodowych'), (19, b'Szko\xc5\x82a policealna (ponadgimnazjalna)'), (20, b'Szko\xc5\x82a specjalna'), (21, b'Sze\xc5\x9bcioletnia og\xc3\xb3lnokszta\xc5\x82c\xc4\x85ca szko\xc5\x82a muzyczna I stopnia'), (22, b'Sze\xc5\x9bcioletnia szko\xc5\x82a muzyczna I stopnia'), (23, b'Czteroletnia szko\xc5\x82a muzyczna I stopnia'), (24, b'Sze\xc5\x9bcioletnia og\xc3\xb3lnokszta\xc5\x82c\xc4\x85ca szko\xc5\x82a muzyczna II stopnia'), (25, b'Sze\xc5\x9bcioletnia szko\xc5\x82a muzyczna II stopnia'), (26, b'Sze\xc5\x9bcioletnia og\xc3\xb3lnokszta\xc5\x82c\xc4\x85ca szko\xc5\x82a sztuk pi\xc4\x99knych'), (27, b'Czteroletnie liceum plastyczne'), (29, b'Dziewi\xc4\x99cioletnia og\xc3\xb3lnokszta\xc5\x82c\xc4\x85ca szko\xc5\x82a baletowa'), (30, b'Sze\xc5\x9bcioletnia szko\xc5\x82a sztuki ta\xc5\x84ca'), (31, b'Czteroletnia szko\xc5\x82a sztuki cyrkowej'), (32, b'Policealna szko\xc5\x82a artystyczna'), (33, b'Szko\xc5\x82a pomaturalna bibliotekarska'), (34, b'Kolegium nauczycielskie'), (35, b'Nauczycielskie Kolegium J\xc4\x99zyk\xc3\xb3w Obcych'), (36, b'O\xc5\x9brodek politechniczny'), (37, b'Pa\xc5\x82ac m\xc5\x82odzie\xc5\xbcy'), (38, b'M\xc5\x82odzie\xc5\xbcowy dom kultury'), (39, b'Ognisko pracy pozaszkolnej'), (40, b'Mi\xc4\x99dzyszkolny o\xc5\x9brodek sportowy'), (41, b'Ogr\xc3\xb3d jordanowski'), (42, b'Pozaszkolna plac\xc3\xb3wka specjalistyczna'), (43, b'Szkolne schronisko m\xc5\x82odzie\xc5\xbcowe'), (44, b'Plac\xc3\xb3wki artystyczne (ognisko artystyczne)'), (45, b'Centrum Kszta\xc5\x82cenia Praktycznego'), (46, b'Centrum Kszta\xc5\x82cenia Ustawicznego ze szko\xc5\x82ami'), (47, b'O\xc5\x9brodek dokszta\xc5\x82cania i doskonalenia zawodowego'), (48, b'Poradnia psychologiczno-pedagogiczna'), (49, b'Poradnia specjalistyczna'), (50, b'Specjalny O\xc5\x9brodek Wychowawczy'), (51, b'Specjalny O\xc5\x9brodek Szkolno-Wychowawczy'), (52, b'O\xc5\x9brodek Rewalidacyjno-Wychowawczy dla upo\xc5\x9bledzonych umys\xc5\x82owo'), (53, b'M\xc5\x82odzie\xc5\xbcowy O\xc5\x9brodek Wychowawczy'), (54, b'M\xc5\x82odzie\xc5\xbcowy O\xc5\x9brodek Socjoterapii ze szko\xc5\x82ami'), (55, b'Bursa'), (56, b'Dom wczas\xc3\xb3w dzieci\xc4\x99cych'), (57, b'Plac\xc3\xb3wka doskonalenia nauczycieli'), (58, b'Biblioteki pedagogiczne'), (59, b'Publiczna plac\xc3\xb3wka opieku\xc5\x84czo-wychowawcza w systemie pomocy spo\xc5\x82ecznej'), (60, b'Zak\xc5\x82ad poprawczy'), (61, b'Schronisko dla nieletnich'), (62, b'Rodzinny o\xc5\x9brodek diagnostyczno-konsultacyjny'), (63, b'Publiczny o\xc5\x9brodek adopcyjno-opieku\xc5\x84czy'), (64, b'Niepubliczna plac\xc3\xb3wka o\xc5\x9bwiatowo-wychowawcza w systemie o\xc5\x9bwiaty'), (65, b'Kolegium Pracownik\xc3\xb3w S\xc5\x82u\xc5\xbcb Spo\xc5\x82ecznych'), (66, b'Szko\xc5\x82a pomaturalna animator\xc3\xb3w kultury'), (67, b'Delegatura'), (68, b'Internat'), (69, b'Czteroletnia szko\xc5\x82a muzyczna II stopnia'), (70, b'Dziewi\xc4\x99cioletnia szko\xc5\x82a sztuki ta\xc5\x84ca'), (73, b'Szko\xc5\x82a specjalna przysposabiaj\xc4\x85ca do pracy na podbudowie 8-letniej szko\xc5\x82y podstawowej'), (74, b'Centrum Kszta\xc5\x82cenia Ustawicznego - bez szk\xc3\xb3\xc5\x82'), (75, b'Niepubliczna plac\xc3\xb3wka kszta\xc5\x82cenia ustawicznego i praktycznego'), (76, b'M\xc5\x82odzie\xc5\xbcowy O\xc5\x9brodek Socjoterapii bez szk\xc3\xb3\xc5\x82'), (80, b'Zesp\xc3\xb3\xc5\x82 wychowania przedszkolnego'), (81, b'Punkt przedszkolny'), (82, b'Pozna\xc5\x84ska szko\xc5\x82a ch\xc3\xb3ralna '), (83, b'Niepubliczna plac\xc3\xb3wka kszta\xc5\x82cenia ustawicznego i praktycznego ze szko\xc5\x82ami'), (90, b'Bednarska Szko\xc5\x82a Realna'), (100, b'Zesp\xc3\xb3\xc5\x82 szk\xc3\xb3\xc5\x82 i plac\xc3\xb3wek o\xc5\x9bwiatowych'), (101, b'Minister'), (102, b'Kuratorium o\xc5\x9bwiaty (wraz z delegaturami)'), (103, b'Jednostka Samorz\xc4\x85du Terytorialnego'), (104, b'ZEAS (zesp\xc3\xb3\xc5\x82 obs\xc5\x82ugi ekonomiczno-administracyjnej szk\xc3\xb3\xc5\x82)'), (105, b'Specjalistyczna jednostka nadzoru'), (106, b'Organ sprawuj\xc4\x85cy nadz\xc3\xb3r pedagogiczny nad zak\xc5\x82adami poprawczymi(\xe2\x80\xa6)'), (107, b'Centralna Komisja Egzaminacyjna'), (108, b'Okr\xc4\x99gowa Komisja Egzaminacyjna')], db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_nr', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('patron', models.CharField(blank=True, max_length=150, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('boys', models.IntegerField(default=0)),
                ('girls', models.IntegerField(default=0)),
                ('agencies', models.IntegerField(default=0)),
                ('fulltime_teachers', models.IntegerField(default=0)),
                ('nonfulltime_teachers', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.City')),
            ],
        ),
    ]
